import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    home: "Home",
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    myOrders: "My Orders",
    reports: "Reports",
    profile: "Profile",
    logout: "Logout",
    welcome: "Welcome",
    editProfile: "Edit Profile",
    fullName: "Full Name",
    email: "Email Address",
    phone: "Phone Number",
    role: "User Role",
    saveChanges: "Save Changes",
    profilePhoto: "Profile Photo",
    uploadPhoto: "Upload Photo",
    loading: "Loading...",
    error: "Error",
    backToDashboard: "Back to Dashboard",
    orderManagement: "Order Management",
    viewAndManageIncoming: "View and manage all your incoming product orders.",
    noOrdersYet: "No orders yet",
    noOrdersYetSub: "When buyers order your products, they will appear here.",
    orderId: "Order ID",
    product: "Product",
    buyer: "Buyer",
    farmer: "Farmer",
    qty: "Qty",
    status: "Status",
    rejectionReason: "Rejection Reason",
    deliveryInfo: "Delivery Info",
    date: "Date",
    action: "Action",
    confirmOrder: "Confirm Order",
    cancelOrder: "Cancel Order",
    sendDeliveryInfo: "Send Delivery Info",
    updateDeliveryInfo: "Update Delivery Info",
    markAsDelivered: "Mark as Delivered",
    rejectOrder: "Reject Order",
    rejectOrderSub: "Please state the reason for rejecting this order (e.g. pre-ordered by another buyer, out of stock, etc.).",
    deliveryInfoTitle: "Delivery Information",
    deliveryInfoSub: "Enter the driver details so the buyer can track their delivery.",
    driverName: "Driver Name",
    driverPhone: "Driver Phone",
    plateNumber: "Plate Number",
    cancel: "Cancel",
    sendToBuyer: "Send to Buyer",
    submitting: "Submitting...",
    sending: "Sending...",
    itemsSold: "Items Sold",
    lowStock: "Low Stock",
    recentOrders: "Recent Orders",
    viewAll: "View all",
    pending: "pending",
    confirmed: "confirmed",
    delivered: "delivered",
    cancelled: "cancelled",
    activeProducts: "Active Products",
    addProduct: "Add Product",
    price: "Price",
    stock: "Stock",
    edit: "Edit",
    delete: "Delete",
    productManagement: "Product Management",
    addUpdateDeleteList: "Add, update, or delete your product listings.",
    reportsTitle: "Sales & Performance Reports",
    reportsSubtitle: "Detailed stats, filters, and sales metrics.",
    totalRevenue: "Total Revenue",
    totalSales: "Total Sales",
    averageOrderValue: "Avg Order Value",
    completedOrders: "Completed Orders",
    salesOverTime: "Sales Over Time",
    orderHistory: "Order History",
    trackStatusHistory: "Track order status and view order history.",
    total: "Total",
    browseProducts: "Browse Products",
    wholesaleMin: "Wholesale Min",
    quantity: "Quantity",
    placeOrder: "Place Order",
    subtotal: "Subtotal",
    orderNow: "Order Now",
    deliveryAddress: "Delivery Address",
    additionalNotes: "Additional Notes",
    updatePhoto: "Update Photo",

    // Home
    heroTitle: "A modern digital market for agriculture",
    heroSubtitle: "AgroBridge gives buyers a reliable way to source quality produce and gives providers a powerful platform to sell directly, manage stock, and scale their business.",
    browseProductBtn: "Browse Product",
    startSellingBtn: "Start Selling",
    twentyFourSeven: "24/7",
    twentyFourSevenDesc: "Marketplace access for buyers and providers.",
    fast: "Fast",
    fastDesc: "Quick ordering flow with login.",
    clear: "Clear",
    clearDesc: "Transparent pricing and stock visibility.",
    tradeSmarterTitle: "Everything you need to trade smarter",
    easyManagement: "Easy Management",
    easyManagementDesc: "Providers can list, edit, and manage stock from a clean dashboard.",
    smartSearch: "Smart Search",
    smartSearchDesc: "Buyers can filter by category, quantity, and location to find exactly what they need.",
    realtimeUpdates: "Real-time Updates",
    realtimeUpdatesDesc: "Get notified instantly when orders are placed, updated, or delivered.",
    readyToJoinTitle: "Ready to join the digital market?",
    readyToJoinDesc: "Thousands of providers and buyers are already trading on AgroBridge.",

    // Home Mockup Screen
    orderPlaced: "Order Placed!",
    justNow: "Just now",
    newListing: "New Listing",
    freshTeffAdded: "Fresh Teff added",
    farmersActive: "5,000+ Farmers",
    activelySelling: "Actively selling",
    searchPlaceholderMock: "Search fresh produce, grains, spices…",
    allFilter: "All",
    grainsFilter: "Grains",
    vegetablesFilter: "Vegetables",
    coffeeFilter: "Coffee",
    spicesFilter: "Spices",
    carrotsMock: "Carrots",
    teffMock: "Teff",
    coffeeMock: "Coffee",
    onionsMock: "Onions",
    kaleMock: "Kale",
    beansMock: "Beans",
    newTag: "New",
    popularTag: "Popular",
    availableMock: "available",
    orderNowMock: "Order Now",
    browseMock: "Browse",
    sellMock: "Sell",
    aboutMock: "About",


    // Login & general auth
    welcomeBack: "Welcome back.",
    loginDesc: "Log in to manage your account, browse products, place orders, or track sales performance.",
    loginFormTitle: "Login",
    loginFormSubtitle: "Use your email and password to access your dashboard.",
    emailLabel: "Email",
    passwordLabel: "Password",
    forgotPasswordLink: "Forgot password?",
    loginBtn: "Login",
    loggingIn: "Logging in...",
    noAccount: "No account?",
    createOne: "Create one.",
    enterEmailPass: "Please enter both email and password.",
    incorrectCredentials: "Incorrect email or password. Please try again.",
    cannotConnectServer: "Cannot connect to the server. Make sure the backend is running.",
    unexpectedError: "An unexpected error occurred. Please try again.",

    // Register
    createAccountTitle: "Create your account.",
    registerDesc: "Join as a Provider to list and manage products, or as a Buyer to browse and place orders.",
    registerFormTitle: "Register",
    registerFormSubtitle: "Fill in your details to create a new account.",
    fullNameLabel: "Full name",
    phoneLabel: "Phone number",
    roleLabel: "Role",
    providerRole: "Provider",
    buyerRole: "Buyer",
    confirmPasswordLabel: "Confirm password",
    createAccountBtn: "Create Account",
    creatingAccount: "Creating Account...",
    alreadyHaveAccount: "Already have an account?",
    logInLink: "Log in.",
    fillRequiredFields: "Please fill in all required fields.",
    passwordsDoNotMatch: "Passwords do not match.",

    // Forgot Password
    resetPasswordTitle: "Reset your password",
    resetPasswordSubtitle: "Enter the email linked to your account. If it exists, we'll send instructions to reset your password.",
    sendResetLinkBtn: "Send reset link",
    sendingLink: "Sending...",
    backToLoginLink: "Back to login",
    enterEmailError: "Please enter your email address.",
    resetInstructionsSent: "If the email exists, reset instructions have been sent.",

    // Reset Password
    resetPasswordFormTitle: "Reset Your Password",
    resetPasswordFormSubtitle: "Please enter your new password below.",
    newPasswordLabel: "New Password",
    confirmNewPasswordLabel: "Confirm Password",
    updatePasswordBtn: "Reset Password",
    resettingBtn: "Resetting...",
    successLabel: "Success:",
    errorLabel: "Error:",
    passwordLengthError: "Password must be at least 8 characters long.",
    missingCredsError: "Invalid password reset link. Missing credentials.",
    missingUidTokenError: "Missing UID or Token from URL.",
    resetSuccessMsg: "Your password has been reset successfully!",
    rememberedPassword: "Remembered your password?",
    logInHere: "Log in here",

    // Browse Products
    browseProductsTitle: "Browse Products",
    browseProductsSubtitle: "Find fresh agriculture produce directly from local providers.",
    searchPlaceholder: "Search products...",
    noProductsFound: "No products found",
    noProductsMatching: "Try adjusting your search query.",
    viewDetailsBtn: "View Details",
    allCategories: "All Categories",
    vegetables: "Vegetables",
    fruits: "Fruits",
    grains: "Grains",
    tubers: "Tubers",
    meatPoultry: "Meat & Poultry",
    dairy: "Dairy",
    others: "Others",
    recommended: "Recommended",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    searchLabel: "Search",
    sortLabel: "Sort By",
    resetBtn: "Reset",
    loadingProducts: "Loading products...",
    inStockStatus: "In Stock",
    lowStockStatus: "Low Stock",
    outOfStockStatus: "Out of Stock",
    viewBtn: "View",
    quickOrderBtn: "Quick Order",
    birrUnit: "Birr",
    noProductsTitle: "No products",
    noProductsSubtitle: "No products are available right now. Try adjusting filters or check back later.",

    // Product Details
    backToProducts: "Back to products",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    wholesaleMinQty: "Wholesale Minimum",
    productDescription: "Description",
    aboutFarmer: "About the Farmer",
    buyerReviewTitle: "Buyer Reviews",
    noReviewsYet: "No reviews yet for this product.",
    noDescription: "No description provided for this product.",
    availableQuantityLabel: "Available Quantity",
    sellerInformation: "Seller Information",
    unknownProvider: "Unknown Provider",
    oopsTitle: "Oops!",
    productNotFound: "Product not found.",

    // Place Order
    placeYourOrderTitle: "Place Your Order",
    placeYourOrderSubtitle: "Review product details and enter delivery specifications.",
    deliveryAddressLabel: "Delivery Address",
    additionalNotesLabel: "Additional Notes",
    orderSummaryTitle: "Order Summary",
    pricePerUnit: "Price per unit",
    subtotalLabel: "Subtotal",
    orderNowBtn: "Order Now",
    orderingBtn: "Ordering...",
    successAlertTitle: "Success",
    orderSuccessMsg: "Order placed successfully!",
    checkingAuth: "Checking authentication...",
    confirmPurchaseSubtitle: "Confirm your purchase.",
    availableLabel: "Available",
    enterQuantityError: "Please enter a quantity.",
    minOrderErrorPrefix: "Minimum order for ",
    minOrderErrorSuffix: " (wholesale requirement).",
    onlyAvailableError: "Only {stock} available in stock.",
    enterPhoneError: "Please enter your phone number so the seller can contact you.",
    totalPriceLabel: "Total Price",
    orderSuccessMessage: "Order Placed Successfully!",
    orderSuccessMessageSub: "Your order has been confirmed.",
    viewMyOrdersBtn: "View My Orders",

    // Provider Orders (Order Management)
    orderManagementTitle: "Order Management",
    orderManagementSubtitle: "View and manage all your incoming product orders.",
    noOrdersYetProvider: "When buyers order your products, they will appear here.",
    couldNotLoadOrders: "Could not load orders. Please try again later.",
    enterRejectionReasonError: "Please provide a reason for rejecting this order.",
    rejectOrderError: "Could not reject the order. Please try again.",
    fillDeliveryInfoError: "Please fill in all delivery information fields.",
    sendDeliveryInfoError: "Could not send delivery info. Check the backend connection.",
    confirmOrderBtn: "Confirm Order",
    updateDeliveryInfoBtn: "Update Delivery Info",
    sendDeliveryInfoBtn: "Send Delivery Info",
    cancelOrderBtn: "Cancel Order",
    deliveryInformationHeader: "Delivery Information",
    deliveryInformationSubtitle: "Enter the driver details so the buyer can track their delivery.",
    driverNameLabel: "Driver Name",
    driverPhoneLabel: "Driver Phone",
    plateNumberLabel: "Plate Number",
    sendToBuyerBtn: "Send to Buyer",
    rejectOrderHeader: "Reject Order",
    rejectionModalSubtitle: "Please state the reason for rejecting this order (e.g. pre-ordered by another buyer, out of stock, etc.).",
    rejectionReasonLabel: "Rejection Reason",

    // Provider Dashboard
    providerDashboardTitle: "Provider Dashboard",
    providerDashboardSubtitle: "Quick overview of your sales, orders, and inventory.",
    ordersLabelDashboard: "Orders",
    itemsSoldLabel: "Items Sold",
    lowStockLabel: "Low Stock",
    pendingOrdersTrend: "{count} pending",
    acrossProductsTrend: "Across {count} products",
    needsRestockingTrend: "Needs restocking",
    allStockedTrend: "All stocked",
    recentOrdersTitle: "Recent Orders",
    viewAllBtn: "View all",
    noOrdersYetDashboard: "No orders yet.",
    updateInventoryBtn: "Update inventory",
    allProductsStockedMsg: "✅ All products are well stocked.",
    remainingLabel: "remaining",
    lowStockBadge: "Low Stock",

    // Product Management
    productManagementTitle: "Product Management",
    productManagementSubtitle: "Add, update, or delete your product listings.",
    addProductBtn: "Add Product",
    deleteProductConfirm: "Are you sure you want to delete \"{name}\"? This action cannot be undone.",
    deleteProductError: "Failed to delete product. Please try again.",
    loadProductsError: "Failed to load products. Please check your connection and try again.",
    noProductsYet: "No products yet.",
    noProductsYetSubtitle: "Click \"Add Product\" to create your first listing.",
    productHeader: "PRODUCT",
    priceHeader: "PRICE",
    stockHeader: "STOCK",
    statusHeader: "STATUS",
    actionsHeader: "ACTIONS",
    updatedToday: "Updated today",
    updatedAt: "Updated {date}",
    editBtn: "Edit",
    deleteBtn: "Delete",
    deleting: "Deleting...",
    retryBtn: "Retry",

    // Add / Edit Product
    editProductTitle: "Edit Product",
    addProductTitle: "Add Product",
    editProductSubtitle: "Update the details for this product.",
    addProductSubtitle: "Create a new listing for your product.",
    backToProductsBtn: "Back to products",
    productDetailsHeader: "Product details",
    productNameLabel: "Product name",
    descriptionLabel: "Description",
    priceLabel: "Price",
    unitLabel: "Unit",
    qtyAvailableLabel: "Quantity available",
    categoryLabel: "Category",
    kilogramUnit: "Kilogram (kg)",
    quintalUnit: "Quintal (q)",
    literUnit: "Liter (l)",
    dozenUnit: "Dozen (dz)",
    saving: "Saving...",
    updateProductBtn: "Update product",
    saveProductBtn: "Save product",
    productImageHeader: "Product image",
    uploadBold: "Upload",
    uploadInstructions: "Drag and drop an image here, or click to browse.",
    chooseFileBtn: "Choose file",
    removeBtn: "Remove",
    invalidDataBadge: "Invalid data",
    fillProductFormError: "Please fill in the product name, price, and quantity.",
    pricePositiveError: "Price must be a positive number.",
    productUpdatedSuccess: "Product updated successfully!",
    productCreatedSuccess: "Product created successfully!",
    loadProductDetailsError: "Failed to load product details. Please try again.",
    saveProductError: "Failed to save product. Please try again.",
    loadingProductDetails: "Loading product details...",
    descriptionPlaceholder: "Describe quality, harvest date, packaging...",
    categoryVegetables: "Vegetables",
    categoryFruits: "Fruits",
    categoryGrains: "Grains",
    categoryTubers: "Tubers",
    categoryMeat: "Meat & Poultry",
    categoryDairy: "Dairy",
    categoryOthers: "Others",

    // Buyer Orders (My Orders)
    buyerOrdersTitle: "My Orders",
    buyerOrdersSubtitle: "Track your product requests and status history.",
    statusPending: "Pending",
    statusConfirmed: "Confirmed",
    statusDelivered: "Delivered",
    statusCancelled: "Cancelled",
    orderDate: "Order Date",
    driverDetails: "Driver Details",
    driverLabel: "Driver",
    phoneLabelShort: "Phone",
    plateLabel: "Plate",
    noOrdersTitle: "No orders placed yet",
    noOrdersSubtitle: "Browse products and make your first order!",

    // Provider Dashboard
    providerDashboardTitle: "Dashboard",
    providerDashboardSubtitle: "Overview of your shop and sales activity.",
    activeProductsCard: "Active Products",
    itemsSoldCard: "Items Sold",
    lowStockCard: "Low Stock",
    recentOrdersTitle: "Recent Orders",

    // Product Management
    manageProductsTitle: "Product Management",
    manageProductsSubtitle: "Add, update, or delete your product listings.",
    pricePerUnitMgmt: "Price/Unit",
    stockMgmt: "Stock",
    editBtn: "Edit",
    deleteBtn: "Delete",
    noProductsListed: "No products listed yet",
    startListingProducts: "Start adding products to showcase them to buyers.",

    // Add Product
    addProductTitle: "Add Product",
    editProductTitle: "Edit Product",
    addProductSubtitle: "Create a new product listing.",
    editProductSubtitle: "Update your product details.",
    productNameLabel: "Product Name",
    categoryLabel: "Category",
    selectCategory: "Select Category",
    priceLabel: "Price",
    unitLabel: "Unit",
    stockLabel: "Stock Quantity",
    wholesaleMinLabel: "Wholesale Min Quantity",
    descriptionLabel: "Description",
    productPhotoLabel: "Product Photo",
    chooseProductPhoto: "Choose Photo",
    creatingProduct: "Creating...",
    updatingProduct: "Updating...",
    saveProductBtn: "Save Product",

    // Reports
    salesReportsTitle: "Sales Reports",
    salesReportsSubtitle: "Insights on product performance and quantities sold.",
    totalRevenueCard: "Total Revenue",
    totalSalesCard: "Total Sales",
    avgOrderValueCard: "Avg Order Value",
    completedOrdersCard: "Completed Orders",
    salesOverTimeTitle: "Sales Over Time",
    orderHistoryTitle: "Order History",
    trackStatusHistorySubtitle: "Track order status and view order history.",
    reportDateRange: "Date Range",
    reportLast30Days: "Last 30 days",
    reportLast7Days: "Last 7 days",
    reportThisYear: "This year",
    reportAllTime: "All time",
    reportAllProducts: "All products",
    reportMetric: "Metric",
    reportMetricRevenue: "Revenue",
    reportMetricQty: "Quantity Sold",
    reportMetricOrders: "Orders",
    reportTopProducts: "Top products by",
    reportChartDescription: "Visual representation of your performance metrics.",
    reportSummary: "Summary",
    reportQtySold: "QTY SOLD",
    exportPDF: "Export PDF",
    reportNoData: "No available report data.",
    reportLoadingData: "Loading reports data...",
    reportFetchingHistory: "Fetching your sales history...",
    reportCouldNotLoad: "Could not load reports:",
    reportNoServerResponse: "No response from server. Check that the backend is running.",
    reportLoadError: "Failed to load report data.",
    unknownProduct: "Unknown Product",

    // Profile
    profileTitle: "Profile",
    profileSubtitle: "Update your personal information.",
    choosePhotoBtn: "Choose Photo",
    removePhotoBtn: "Remove",
    photoInstructionsText: "JPG, PNG or GIF. Max size 2MB.",
    fullNameLabelProfile: "Full name",
    phoneLabelProfile: "Phone number",
    emailLabelProfile: "Email",
    roleLabelProfile: "Role",
    cancelBtn: "Cancel",
    saveChangesBtn: "Save changes",
    savingChanges: "Saving...",
    logoutLinkText: "Logout from account",
    imageSizeError: "Image size must be less than 2MB.",
    profileUpdateSuccess: "Your profile has been updated successfully.",
    profileUpdateFail: "Failed to update profile. Please try again.",
    buyerOrdersError: "Could not load your orders. Please try again later.",
    orderUpdateFail: "Could not update order status. Please try again.",
    copyrightText: "© 2026 AgroBridge. All rights reserved.",
  },
  am: {
    home: "ዋና ገጽ",
    dashboard: "ዳሽቦርድ",
    products: "ምርቶች",
    orders: "ትዕዛዞች",
    myOrders: "የእኔ ትዕዛዞች",
    reports: "ሪፖርቶች",
    profile: "መገለጫ",
    logout: "ውጣ",
    welcome: "እንኳን ደህና መጡ",
    editProfile: "መገለጫ አዘምን",
    fullName: "ሙሉ ስም",
    email: "ኢሜይል አድራሻ",
    phone: "ስልክ ቁጥር",
    role: "የተጠቃሚ ሚና",
    saveChanges: "ለውጦችን አስቀምጥ",
    profilePhoto: "የመገለጫ ፎቶ",
    uploadPhoto: "ፎቶ ለመጫን",
    loading: "በመጫን ላይ...",
    error: "ስህተት",
    backToDashboard: "ወደ ዳሽቦርድ ይመለሱ",
    orderManagement: "የትዕዛዝ አስተዳደር",
    viewAndManageIncoming: "ሁሉንም ገቢ የሆኑ የምርት ትዕዛዞችዎን እዚህ ይመልከቱ እና ያስተዳድሩ።",
    noOrdersYet: "እስካሁን ምንም ትዕዛዝ የለም",
    noOrdersYetSub: "ገዢዎች ምርትዎን ሲያዝዙ፣ እዚህ ይታያሉ።",
    orderId: "የትዕዛዝ መለያ",
    product: "ምርት",
    buyer: "ገዢ",
    farmer: "አምራች/ገበሬ",
    qty: "ብዛት",
    status: "ሁኔታ",
    rejectionReason: "የተሰረዘበት ምክንያት",
    deliveryInfo: "የአቅርቦት መረጃ",
    date: "ቀን",
    action: "እርምጃ",
    confirmOrder: "ትዕዛዝ አረጋግጥ",
    cancelOrder: "ትዕዛዝ ሰርዝ",
    sendDeliveryInfo: "የአቅርቦት መረጃ ላክ",
    updateDeliveryInfo: "የአቅርቦት መረጃ አዘምን",
    markAsDelivered: "የደረሰ መሆኑን አረጋግጥ",
    rejectOrder: "ትዕዛዝ ውድቅ አድርግ",
    rejectOrderSub: "እባክዎን ይህንን ትዕዛዝ ውድቅ ያደረጉበትን ምክንያት ይግለጹ (ምሳሌ፡ በሌላ ገዢ አስቀድሞ የታዘዘ፣ ምርት ያለቀበት ወዘተ)",
    deliveryInfoTitle: "የአቅርቦት (የመጫኛ) መረጃ",
    deliveryInfoSub: "ገዢው አቅርቦቱን እንዲከታተል የሹፌሩን ዝርዝር መረጃ ያስገቡ።",
    driverName: "የሹፌር ስም",
    driverPhone: "የሹፌር ስልክ",
    plateNumber: "የሰሌዳ ቁጥር",
    cancel: "ሰርዝ",
    sendToBuyer: "ለገዢው ላክ",
    submitting: "በማስገባት ላይ...",
    sending: "በመላክ ላይ...",
    itemsSold: "የተሸጡ ምርቶች",
    lowStock: "ክምችት ያለቀባቸው",
    recentOrders: "የቅርብ ጊዜ ትዕዛዞች",
    viewAll: "ሁሉንም አሳይ",
    pending: "በመጠባበቅ ላይ",
    confirmed: "የተረጋገጠ",
    delivered: "የደረሰ",
    cancelled: "የተሰረዘ",
    activeProducts: "ንቁ ምርቶች",
    addProduct: "ምርት ጨምር",
    price: "ዋጋ",
    stock: "ክምችት",
    edit: "አዘምን",
    delete: "ሰርዝ",
    productManagement: "የምርት አስተዳደር",
    addUpdateDeleteList: "የምርት ዝርዝሮችዎን እዚህ ይጨምሩ፣ ያዘምኑ ወይም ይሰርዙ።",
    reportsTitle: "የሽያጭ እና አፈጻጸም ሪፖርቶች",
    reportsSubtitle: "ዝርዝር ስታቲስቲክስ፣ ማጣሪያዎች እና የሽያጭ መለኪያዎች።",
    totalRevenue: "ጠቅላላ ገቢ",
    totalSales: "ጠቅላላ ሽያጭ",
    averageOrderValue: "አማካይ የትዕዛዝ ዋጋ",
    completedOrders: "የተጠናቀቁ ትዕዛዞች",
    salesOverTime: "ሽያጭ በጊዜ ሂደት",
    orderHistory: "የትዕዛዝ ታሪክ",
    trackStatusHistory: "የትዕዛዝ ሁኔታን ይከታተሉ እና የትዕዛዝ ታሪክዎን ይመልከቱ።",
    total: "ጠቅላላ",
    browseProducts: "ምርቶችን ይፈልጉ",
    wholesaleMin: "ዝቅተኛ የጅምላ ትዕዛዝ",
    quantity: "ብዛት",
    placeOrder: "ትዕዛዝ ይዘዙ",
    subtotal: "ድምር ዋጋ",
    orderNow: "አሁን እዘዝ",
    deliveryAddress: "የማድረሻ አድራሻ",
    additionalNotes: "ተጨማሪ ማስታወሻ",
    updatePhoto: "ፎቶ አዘምን",

    // Home
    heroTitle: "ዘመናዊ የግብርና ዲጂታል የገበያ ቦታ",
    heroSubtitle: "አግሮብሪጅ ለገዢዎች ጥራት ያላቸውን ምርቶች አስተማማኝ በሆነ መንገድ እንዲያገኙ የሚያስችል ሲሆን ለአምራቾች ደግሞ ምርቶቻቸውን በቀጥታ ለመሸጥ፣ ክምችት ለማስተዳደርና ንግዳቸውን ለማሳደግ የሚያግዝ ጠንካራ መድረክ ይሰጣል።",
    browseProductBtn: "ምርቶችን ፈልግ",
    startSellingBtn: "መሸጥ ይጀምሩ",
    twentyFourSeven: "24/7",
    twentyFourSevenDesc: "ለገዢዎችና ለአምራቾች የ24/7 የገበያ መዳረሻ።",
    fast: "ፈጣን",
    fastDesc: "በመለያ በመግባት ፈጣን የትዕዛዝ ሂደት።",
    clear: "ግልጽ",
    clearDesc: "ግልጽ የዋጋ አሰጣጥ እና የክምችት ታይነት።",
    tradeSmarterTitle: "በብልሃት ለመገበያየት የሚያስፈልጉዎት ነገሮች ሁሉ",
    easyManagement: "ቀላል አስተዳደር",
    easyManagementDesc: "አቅራቢዎች ንጹህ በሆነ ዳሽቦርድ ላይ ምርቶችን መመዝገብ፣ ማስተካከል እና ክምችት ማስተዳደር ይችላሉ።",
    smartSearch: "ዘመናዊ ፍለጋ",
    smartSearchDesc: "ገዢዎች የሚፈልጉትን በትክክል ለማግኘት በምድብ፣ በብዛት እና በቦታ መለየት ይችላሉ።",
    realtimeUpdates: "የቀጥታ ሰዓት ዝመናዎች",
    realtimeUpdatesDesc: "ትዕዛዞች ሲቀመጡ፣ ሲዘምኑ ወይም ሲደርሱ ወዲያውኑ ማሳወቂያዎችን ያግኙ።",
    readyToJoinTitle: "ዲጂታል ገበያውን ለመቀላቀል ዝግጁ ነዎት?",
    readyToJoinDesc: "በሺዎች የሚቆጠሩ አቅራቢዎች እና ገዢዎች ቀድሞውኑ በአግሮብሪጅ ላይ እየተገበያዩ ነው።",

    // Home Mockup Screen
    orderPlaced: "ትዕዛዝ ተቀምጧል!",
    justNow: "አሁን",
    newListing: "አዲስ ምርት",
    freshTeffAdded: "ትኩስ ጤፍ ተጨምሯል",
    farmersActive: "5,000+ አምራቾች",
    activelySelling: "ንቁ ሽያጭ ላይ",
    searchPlaceholderMock: "ትኩስ ምርቶችን፣ ጥራጥሬዎችን፣ ቅመማ ቅመሞችን ፈልግ...",
    allFilter: "ሁሉንም",
    grainsFilter: "ጥራጥሬዎች",
    vegetablesFilter: "አትክልቶች",
    coffeeFilter: "ቡና",
    spicesFilter: "ቅመማ ቅመም",
    carrotsMock: "ካሮት",
    teffMock: "ጤፍ",
    coffeeMock: "ቡና",
    onionsMock: "ሽንኩርት",
    kaleMock: "ጎመን",
    beansMock: "ባቄላ/አተር",
    newTag: "አዲስ",
    popularTag: "ተወዳጅ",
    availableMock: "ያለ መጠን",
    orderNowMock: "አሁን እዘዝ",
    browseMock: "ፈልግ",
    sellMock: "ሽጥ",
    aboutMock: "ስለ እኛ",


    // Login & general auth
    welcomeBack: "እንኳን ደህና መጡ።",
    loginDesc: "መለያዎን ለማስተዳደር፣ ምርቶችን ለመፈለግ፣ ትዕዛዞችን ለመሰረዝ ወይም የሽያጭ አፈጻጸምን ለመከታተል ይግቡ።",
    loginFormTitle: "ይግቡ",
    loginFormSubtitle: "ዳሽቦርድዎን ለመጠቀም የኢሜይል እና የይለፍ ቃልዎን ያስገቡ።",
    emailLabel: "ኢሜይል",
    passwordLabel: "የይለፍ ቃል",
    forgotPasswordLink: "የይለፍ ቃልዎን ረስተዋል?",
    loginBtn: "ይግቡ",
    loggingIn: "በመግባት ላይ...",
    noAccount: "መለያ የለዎትም?",
    createOne: "አዲስ ይፍጠሩ።",
    enterEmailPass: "እባክዎን ኢሜይል እና የይለፍ ቃል ያስገቡ።",
    incorrectCredentials: "ኢሜይሉ ወይም የይለፍ ቃሉ ትክክል አይደለም። እባክዎን እንደገና ይሞክሩ።",
    cannotConnectServer: "ወደ አገልጋዩ መገናኘት አልተቻለም። ባክኤንዱ እየሰራ መሆኑን ያረጋግጡ።",
    unexpectedError: "ያልተጠበቀ ስህተት ተከስቷል። እባክዎን እንደገና ይሞክሩ።",

    // Register
    createAccountTitle: "መለያዎን ይፍጠሩ።",
    registerDesc: "ምርቶችን ለመመዝገብ እና ለማስተዳደር በአምራችነት፣ ወይም ምርቶችን ለመፈለግ እና ለማዘዝ በገዢነት ይቀላቀሉን።",
    registerFormTitle: "ይመዝገቡ",
    registerFormSubtitle: "አዲስ መለያ ለመፍጠር ዝርዝር መረጃዎን ያስገቡ።",
    fullNameLabel: "ሙሉ ስም",
    phoneLabel: "ስልክ ቁጥር",
    roleLabel: "ሚና",
    providerRole: "አቅራቢ/አምራች",
    buyerRole: "ገዢ",
    confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
    createAccountBtn: "መለያ ፍጠር",
    creatingAccount: "መለያ በመፍጠር ላይ...",
    alreadyHaveAccount: "መለያ አለዎት?",
    logInLink: "ይግቡ።",
    fillRequiredFields: "እባክዎን ሁሉንም አስፈላጊ ቦታዎች ይሙሉ",
    passwordsDoNotMatch: "የይለፍ ቃላቱ አይዛመዱም።",

    // Forgot Password
    resetPasswordTitle: "የይለፍ ቃልዎን ይቀይሩ",
    resetPasswordSubtitle: "ከመለያዎ ጋር የተገናኘውን ኢሜይል ያስገቡ። መለያው ካለ የይለፍ ቃልዎን ለመቀየር መመሪያ እንልካለን።",
    sendResetLinkBtn: "የመቀየሪያ ሊንክ ላክ",
    sendingLink: "በመላክ ላይ...",
    backToLoginLink: "ወደ መግቢያ ተመለስ",
    enterEmailError: "እባክዎን የኢሜይል አድራሻዎን ያስገቡ።",
    resetInstructionsSent: "ኢሜይሉ ከተገኘ የይለፍ ቃል መቀየሪያ መመሪያ ተልኳል።",

    // Reset Password
    resetPasswordFormTitle: "የይለፍ ቃል መቀየር",
    resetPasswordFormSubtitle: "እባክዎን አዲሱን የይለፍ ቃልዎን ከታች ያስገቡ።",
    newPasswordLabel: "አዲስ የይለፍ ቃል",
    confirmNewPasswordLabel: "አዲስ የይለፍ ቃል ያረጋግጡ",
    updatePasswordBtn: "የይለፍ ቃል አዘምን",
    resettingBtn: "በመቀየር ላይ...",
    successLabel: "ስኬት:",
    errorLabel: "ስህተት:",
    passwordLengthError: "የይለፍ ቃል ቢያንስ 8 ፊደላት መሆን አለበት።",
    missingCredsError: "የማይሰራ የይለፍ ቃል መቀየሪያ ሊንክ።",
    missingUidTokenError: "የማይሰራ ዩአይዲ ወይም ቶከን።",
    resetSuccessMsg: "የይለፍ ቃልዎ በተሳካ ሁኔታ ተቀይሯል!",
    rememberedPassword: "የይለፍ ቃልዎን ያስታውሳሉ?",
    logInHere: "እዚህ ይግቡ",

    // Browse Products
    browseProductsTitle: "ምርቶችን ይፈልጉ",
    browseProductsSubtitle: "ትኩስ የግብርና ምርቶችን በቀጥታ ከአካባቢዎ አምራቾች ያግኙ።",
    searchPlaceholder: "ምርቶችን ይፈልጉ...",
    noProductsFound: "ምንም ምርት አልተገኘም",
    noProductsMatching: "እባክዎን የፍለጋ ቃልዎን ያስተካክሉ።",
    viewDetailsBtn: "ዝርዝር ይመልከቱ",
    allCategories: "ሁሉንም ምድቦች",
    vegetables: "አትክልቶች",
    fruits: "ፍራፍሬዎች",
    grains: "ጥራጥሬዎች",
    tubers: "ስሮችና ስራሥሮች",
    meatPoultry: "ስጋ እና የዶሮ እርባታ",
    dairy: "የወተት ተዋጽኦ",
    others: "ሌሎች",
    recommended: "የተመከሩ",
    priceLowHigh: "ዋጋ፡ ከዝቅተኛ ወደ ከፍተኛ",
    priceHighLow: "ዋጋ፡ ከከፍተኛ ወደ ዝቅተኛ",
    searchLabel: "ፈልግ",
    sortLabel: "በ... ደርድር",
    resetBtn: "እንደገና ጀምር",
    loadingProducts: "ምርቶች በመጫን ላይ...",
    inStockStatus: "ክምችት አለ",
    lowStockStatus: "ክምችት ያነሰ",
    outOfStockStatus: "ክምችት የለም",
    viewBtn: "እይ",
    quickOrderBtn: "ፈጣን ትዕዛዝ",
    birrUnit: "ብር",
    noProductsTitle: "ምንም ምርት የለም",
    noProductsSubtitle: "በአሁኑ ጊዜ ምንም ምርቶች አይገኙም። ማጣሪያዎችን ለማስተካከል ይሞክሩ ወይም ቆይተው እንደገና ይመልከቱ።",

    // Product Details
    backToProducts: "ወደ ምርቶች ተመለስ",
    outOfStock: "ክምችት አልቋል",
    inStock: "ክምችት አለ",
    wholesaleMinQty: "ዝቅተኛ የጅምላ ትዕዛዝ",
    productDescription: "መግለጫ",
    aboutFarmer: "ስለ አምራቹ/ገበሬው",
    buyerReviewTitle: "የገዢዎች አስተያየት",
    noReviewsYet: "ለዚህ ምርት እስካሁን የተሰጠ አስተያየት የለም።",
    noDescription: "ለዚህ ምርት ምንም መግለጫ አልተሰጠም።",
    availableQuantityLabel: "ያለው የምርት መጠን",
    sellerInformation: "የሻጭ መረጃ",
    unknownProvider: "ያልታወቀ አቅራቢ",
    oopsTitle: "ውይ!",
    productNotFound: "ምርቱ አልተገኘም።",

    // Place Order
    placeYourOrderTitle: "ትዕዛዝዎን ያስገቡ",
    placeYourOrderSubtitle: "የምርት ዝርዝሩን ያረጋግጡ እና የማድረሻ መረጃ ያስገቡ።",
    deliveryAddressLabel: "የማድረሻ አድራሻ",
    additionalNotesLabel: "ተጨማሪ ማስታወሻዎች",
    orderSummaryTitle: "የትዕዛዝ ማጠቃለያ",
    pricePerUnit: "የአንዱ ዋጋ",
    subtotalLabel: "ድምር ዋጋ",
    orderNowBtn: "አሁን እዘዝ",
    orderingBtn: "በማዘዝ ላይ...",
    successAlertTitle: "ተሳክቷል",
    orderSuccessMsg: "ትዕዛዝዎ በተሳካ ሁኔታ ተቀምጧል!",
    checkingAuth: "ማንነትዎን በማረጋገጥ ላይ...",
    confirmPurchaseSubtitle: "ግዢዎን ያረጋግጡ።",
    availableLabel: "ያለው መጠን",
    enterQuantityError: "እባክዎን መጠን ያስገቡ።",
    minOrderErrorPrefix: "ዝቅተኛው የትዕዛዝ መጠን ለ ",
    minOrderErrorSuffix: " (የጅምላ ሽያጭ መስፈርት)።",
    onlyAvailableError: "ክምችት ውስጥ ያለው {stock} ብቻ ነው።",
    enterPhoneError: "እባክዎን ሻጩ ሊያገኝዎት የሚችልበትን ስልክ ቁጥር ያስገቡ።",
    totalPriceLabel: "ጠቅላላ ዋጋ",
    orderSuccessMessage: "ትዕዛዝዎ በተሳካ ሁኔታ ተቀምጧል!",
    orderSuccessMessageSub: "ትዕዛዝዎ ተረጋግጧል።",
    viewMyOrdersBtn: "የእኔን ትዕዛዞች እይ",

    // Provider Orders (Order Management)
    orderManagementTitle: "የትዕዛዝ አስተዳደር",
    orderManagementSubtitle: "ገቢ የሆኑ የምርት ትዕዛዞችን እዚህ ይመልከቱ እና ያስተዳድሩ።",
    noOrdersYetProvider: "ገዢዎች የእርስዎን ምርቶች ሲያዙ እዚህ ይገለጣሉ።",
    couldNotLoadOrders: "ትዕዛዞችን መጫን አልተቻለም። እባክዎን ቆይተው እንደገና ይሞክሩ።",
    enterRejectionReasonError: "እባክዎን ይህንን ትዕዛዝ የሚሰርዙበትን ምክንያት ያስገቡ።",
    rejectOrderError: "ትዕዛዙን መሰረዝ አልተቻለም። እባክዎን እንደገና ይሞክሩ።",
    fillDeliveryInfoError: "እባክዎን ሁሉንም የማድረሻ መረጃዎችን ይሙሉ።",
    sendDeliveryInfoError: "የማድረሻ መረጃ መላክ አልተቻለም። የአገልጋይ ግንኙነትዎን ያረጋግጡ።",
    confirmOrderBtn: "ትዕዛዝ አረጋግጥ",
    updateDeliveryInfoBtn: "የማድረሻ መረጃ አዘምን",
    sendDeliveryInfoBtn: "የማድረሻ መረጃ ላክ",
    cancelOrderBtn: "ትዕዛዝ ሰርዝ",
    deliveryInformationHeader: "የማድረሻ መረጃ",
    deliveryInformationSubtitle: "ገዢው ማድረሻውን መከታተል እንዲችል የአሽከርካሪውን ዝርዝር ያስገቡ።",
    driverNameLabel: "የአሽከርካሪ ስም",
    driverPhoneLabel: "የአሽከርካሪ ስልክ ቁጥር",
    plateNumberLabel: "የሰሌዳ ቁጥር",
    sendToBuyerBtn: "ለገዢው ላክ",
    rejectOrderHeader: "ትዕዛዝ ውድቅ አድርግ",
    rejectionModalSubtitle: "እባክዎን ይህንን ትዕዛዝ ውድቅ ለማድረግ የፈለጉበትን ምክንያት ይግለጹ (ለምሳሌ፡ በሌላ ገዢ የታዘዘ፣ ክምችት ያለቀ፣ ወዘተ)።",
    rejectionReasonLabel: "የውድቅ የተደረገበት ምክንያት",

    // Provider Dashboard
    providerDashboardTitle: "የአቅራቢ ዳሽቦርድ",
    providerDashboardSubtitle: "የሽያጭ፣ የትዕዛዝ እና የክምችት ፈጣን ማጠቃለያ።",
    ordersLabelDashboard: "ትዕዛዞች",
    itemsSoldLabel: "የተሸጡ ምርቶች",
    lowStockLabel: "ዝቅተኛ ክምችት",
    pendingOrdersTrend: "{count} በመጠባበቅ ላይ",
    acrossProductsTrend: "በ{count} ምርቶች ውስጥ",
    needsRestockingTrend: "ክምችት ማደስ ያስፈልገዋል",
    allStockedTrend: "ሁሉም ክምችት ሙሉ ነው",
    recentOrdersTitle: "የቅርብ ጊዜ ትዕዛዞች",
    viewAllBtn: "ሁሉንም እይ",
    noOrdersYetDashboard: "እስካሁን ምንም ትዕዛዝ የለም።",
    updateInventoryBtn: "ክምችት አዘምን",
    allProductsStockedMsg: "✅ ሁሉም ምርቶች በደንብ ተከማችተዋል።",
    remainingLabel: "የቀረ",
    lowStockBadge: "ዝቅተኛ ክምችት",

    // Product Management
    productManagementTitle: "የምርት አስተዳደር",
    productManagementSubtitle: "ምርቶችዎን እዚህ ይጨምሩ፣ ያዘምኑ ወይም ይሰርዙ።",
    addProductBtn: "ምርት ጨምር",
    deleteProductConfirm: "\"{name}\" መሰረዝዎን እርግጠኛ ነዎት? ይህ ድርጊት ሊመለስ አይችልም።",
    deleteProductError: "ምርቱን መሰረዝ አልተቻለም። እባክዎን እንደገና ይሞክሩ።",
    loadProductsError: "ምርቶችን መጫን አልተቻለም። እባክዎን ግንኙነትዎን ያረጋግጡና እንደገና ይሞክሩ።",
    noProductsYet: "እስካሁን ምንም ምርት የለም።",
    noProductsYetSubtitle: "የመጀመሪያውን ምርት ለማስገባት \"ምርት ጨምር\" የሚለውን ይጫኑ።",
    productHeader: "ምርት",
    priceHeader: "ዋጋ",
    stockHeader: "ክምችት",
    statusHeader: "ሁኔታ",
    actionsHeader: "እርምጃዎች",
    updatedToday: "ዛሬ ተዘምኗል",
    updatedAt: "በ{date} ተዘምኗል",
    editBtn: "አስተካክል",
    deleteBtn: "ሰርዝ",
    deleting: "በመሰረዝ ላይ...",
    retryBtn: "እንደገና ሞክር",

    // Add / Edit Product
    editProductTitle: "ምርት አስተካክል",
    addProductTitle: "ምርት ጨምር",
    editProductSubtitle: "የዚህን ምርት ዝርዝሮች እዚህ ያዘምኑ።",
    addProductSubtitle: "ለሽያጭ የሚሆን አዲስ ምርት እዚህ ይመዝግቡ።",
    backToProductsBtn: "ወደ ምርቶች ተመለስ",
    productDetailsHeader: "የምርት ዝርዝሮች",
    productNameLabel: "የምርት ስም",
    descriptionLabel: "መግለጫ",
    priceLabel: "ዋጋ",
    unitLabel: "መለኪያ",
    qtyAvailableLabel: "የሚገኘው መጠን",
    categoryLabel: "ምድብ",
    kilogramUnit: "ኪሎግራም (ኪ.ግ)",
    quintalUnit: "ኩንታል (ኩ)",
    literUnit: "ሊትር (ሊ)",
    dozenUnit: "ደርዘን (ደ)",
    saving: "በማስቀመጥ ላይ...",
    updateProductBtn: "ምርት አዘምን",
    saveProductBtn: "ምርት አስቀምጥ",
    productImageHeader: "የምርት ፎቶ",
    uploadBold: "ስቀል",
    uploadInstructions: "ፎቶ እዚህ ይጎትቱ ወይም ለመምረጥ ይጫኑ።",
    chooseFileBtn: "ፎቶ ምረጥ",
    removeBtn: "አስወግድ",
    invalidDataBadge: "ያልተሟላ መረጃ",
    fillProductFormError: "እባክዎን የምርት ስም፣ ዋጋ እና መጠን ያስገቡ።",
    pricePositiveError: "ዋጋ ከዜሮ በላይ መሆን አለበት።",
    productUpdatedSuccess: "ምርቱ በተሳካ ሁኔታ ተዘምኗል!",
    productCreatedSuccess: "ምርቱ በተሳካ ሁኔታ ተፈጥሯል!",
    loadProductDetailsError: "የምርት ዝርዝሮችን መጫን አልተቻለም። እባክዎን እንደገና ይሞክሩ።",
    saveProductError: "ምርቱን ማስቀመጥ አልተቻለም። እባክዎን እንደገና ይሞክሩ።",
    loadingProductDetails: "የምርት ዝርዝሮችን በመጫን ላይ...",
    descriptionPlaceholder: "ስለ ጥራት፣ የአጨዳ ቀን፣ ማሸጊያ... ይግለጹ",
    categoryVegetables: "አትክልት",
    categoryFruits: "ፍራፍሬ",
    categoryGrains: "ጥራጥሬ",
    categoryTubers: "ስርወ-ምርት (ቱበርስ)",
    categoryMeat: "ስጋ እና የዶሮ እርባታ",
    categoryDairy: "የወተት ተዋጽኦ",
    categoryOthers: "ሌሎች",

    // Buyer Orders (My Orders)
    buyerOrdersTitle: "የእኔ ትዕዛዞች",
    buyerOrdersSubtitle: "የምርት ጥያቄዎችዎን እና የሁኔታ ታሪክን ይከታተሉ።",
    statusPending: "በመጠባበቅ ላይ",
    statusConfirmed: "የተረጋገጠ",
    statusDelivered: "የደረሰ",
    statusCancelled: "የተሰረዘ",
    orderDate: "የታዘዘበት ቀን",
    driverDetails: "የሹፌር መረጃ",
    driverLabel: "ሹፌር",
    phoneLabelShort: "ስልክ",
    plateLabel: "የሰሌዳ ቁጥር",
    noOrdersTitle: "እስካሁን ምንም ትዕዛዝ አልተቀመጠም",
    noOrdersSubtitle: "ምርቶችን ይፈልጉ እና የመጀመሪያ ትዕዛዝዎን ያስገቡ!",

    // Provider Dashboard
    providerDashboardTitle: "ዳሽቦርድ",
    providerDashboardSubtitle: "የሱቅዎ እና የሽያጭ እንቅስቃሴዎ አጠቃላይ እይታ።",
    activeProductsCard: "ንቁ ምርቶች",
    itemsSoldCard: "የተሸጡ ምርቶች",
    lowStockCard: "ክምችት ያለቀባቸው",
    recentOrdersTitle: "የቅርብ ጊዜ ትዕዛዞች",

    // Product Management
    manageProductsTitle: "የምርት አስተዳደር",
    manageProductsSubtitle: "የምርት ዝርዝሮችዎን እዚህ ይጨምሩ፣ ያዘምኑ ወይም ይሰርዙ።",
    pricePerUnitMgmt: "ዋጋ/እቃዎች",
    stockMgmt: "ክምችት",
    editBtn: "አዘምን",
    deleteBtn: "ሰርዝ",
    noProductsListed: "እስካሁን ምንም ምርት አልተመዘገበም",
    startListingProducts: "ለገዢዎች ለማሳየት ምርቶችን መመዝገብ ይጀምሩ።",

    // Add Product
    addProductTitle: "ምርት ጨምር",
    editProductTitle: "ምርት አዘምን",
    addProductSubtitle: "አዲስ የሽያጭ ምርት ይመዝግቡ።",
    editProductSubtitle: "የምርት ዝርዝር መረጃዎን ያዘምኑ።",
    productNameLabel: "የምርት ስም",
    categoryLabel: "ምድብ",
    selectCategory: "ምድብ ይምረጡ",
    priceLabel: "ዋጋ",
    unitLabel: "መለኪያ",
    stockLabel: "የክምችት ብዛት",
    wholesaleMinLabel: "ዝቅተኛ የጅምላ ትዕዛዝ",
    descriptionLabel: "መግለጫ",
    productPhotoLabel: "የምርት ፎቶ",
    chooseProductPhoto: "ፎቶ ይምረጡ",
    creatingProduct: "በመፍጠር ላይ...",
    updatingProduct: "በማዘመን ላይ...",
    saveProductBtn: "ምርቱን አስቀምጥ",

    // Reports
    salesReportsTitle: "የሽያጭ ሪፖርቶች",
    salesReportsSubtitle: "ስለ ምርት አፈጻጸም እና የተሸጡ ብዛቶች ማስረጃ።",
    totalRevenueCard: "ጠቅላላ ገቢ",
    totalSalesCard: "ጠቅላላ ሽያጭ",
    avgOrderValueCard: "አማካይ የትዕዛዝ ዋጋ",
    completedOrdersCard: "የተጠናቀቁ ትዕዛዞች",
    salesOverTimeTitle: "ሽያጭ በጊዜ ሂደት",
    orderHistoryTitle: "የትዕዛዝ ታሪክ",
    trackStatusHistorySubtitle: "የትዕዛዝ ሁኔታን ይከታተሉ እና የትዕዛዝ ታሪክዎን ይመልከቱ።",
    reportDateRange: "የቀን ክልል",
    reportLast30Days: "ያለፉት 30 ቀናት",
    reportLast7Days: "ያለፉት 7 ቀናት",
    reportThisYear: "በዚህ ዓመት",
    reportAllTime: "ሁሉም ጊዜ",
    reportAllProducts: "ሁሉም ምርቶች",
    reportMetric: "መለኪያ",
    reportMetricRevenue: "ገቢ",
    reportMetricQty: "የተሸጠ ብዛት",
    reportMetricOrders: "ትዕዛዞች",
    reportTopProducts: "ምርጥ ምርቶች በ",
    reportChartDescription: "የአፈጻጸም መለኪያዎችዎ ምስላዊ ውክልና።",
    reportSummary: "ማጠቃለያ",
    reportQtySold: "የተሸጠ ብዛት",
    exportPDF: "PDF ላክ",
    reportNoData: "ምንም ሪፖርት ዳታ የለም።",
    reportLoadingData: "የሪፖርት ዳታ በመጫን ላይ...",
    reportFetchingHistory: "የሽያጭ ታሪክዎን በማምጣት ላይ...",
    reportCouldNotLoad: "ሪፖርቶችን መጫን አልተቻለም:",
    reportNoServerResponse: "ከአገልጋዩ ምላሽ የለም። ባክኤንዱ እየሰራ መሆኑን ያረጋግጡ።",
    reportLoadError: "የሪፖርት ዳታ መጫን አልተቻለም።",
    unknownProduct: "ያልታወቀ ምርት",

    // Profile
    profileTitle: "መገለጫ",
    profileSubtitle: "የግል መረጃዎን ያዘምኑ።",
    choosePhotoBtn: "ፎቶ ይምረጡ",
    removePhotoBtn: "አስወግድ",
    photoInstructionsText: "JPG, PNG ወይም GIF። ከፍተኛ መጠን 2MB።",
    fullNameLabelProfile: "ሙሉ ስም",
    phoneLabelProfile: "ስልክ ቁጥር",
    emailLabelProfile: "ኢሜይል",
    roleLabelProfile: "ሚና",
    cancelBtn: "ሰርዝ",
    saveChangesBtn: "ለውጦችን አስቀምጥ",
    savingChanges: "በማስቀመጥ ላይ...",
    logoutLinkText: "ከመለያ ውጣ",
    imageSizeError: "የፎቶ መጠን ከ2MB ማነስ አለበት።",
    profileUpdateSuccess: "መገለጫዎ በተሳካ ሁኔታ ተዘምኗል።",
    profileUpdateFail: "መገለጫውን ለማዘመን አልተሳካም። እባክዎን እንደገና ይሞክሩ።",
    buyerOrdersError: "ትዕዛዞችዎን መጫን አልተቻለም። እባክዎን ቆይተው እንደገና ይሞክሩ።",
    orderUpdateFail: "የትዕዛዝ ሁኔታን ማዘመን አልተቻለም። እባክዎን እንደገና ይሞክሩ።",
    copyrightText: "© 2026 አግሮብሪጅ። መብቱ በሕግ የተጠበቀ ነው።",
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("app_language") || "en";
  });

  const toggleLanguage = () => {
    const nextLang = language === "en" ? "am" : "en";
    setLanguage(nextLang);
    localStorage.setItem("app_language", nextLang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
