# Generated by Django 6.0.3 on 2026-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('buyer', 'Buyer')], default='buyer', max_length=10, null=True),
        ),
    ]
