# Generated by Django 6.0.3 on 2026-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='farmer',
            new_name='provider',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('provider', 'Provider'), ('buyer', 'Buyer')], default='buyer', max_length=10, null=True),
        ),
    ]
