# Generated by Django 6.0.3 on 2026-05-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_farmer_product_provider_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('q', 'Quintal (q)'), ('l', 'Liter (l)'), ('dz', 'Dozen (dz)')], default='kg', max_length=10),
        ),
    ]
