# Generated by Django 6.0.3 on 2026-05-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('q', 'Quintal (q)'), ('l', 'Liter (l)'), ('dz', 'Dozen (dz)')], default='kg', max_length=10),
        ),
    ]
