# Generated by Django 6.0.3 on 2026-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_plate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
